# Define services (containers) to run
services:
  # Logical name of the service
  rocm-whisper-api-service:
    # Docker image name and tag to use
    # This assumes the image has been pre-built with 'docker build -t rocm-whisper-api:latest .'
    image: RmG152/rocm-whisper-api:latest
    # Fix the container name as 'rocm-whisper-api'
    container_name: rocm-whisper-api
    # Always restart the container if it stops (except when manually stopped)
    restart: unless-stopped
    # Connect host and container ports (host:container)
    ports:
      - "8080:8080"
    # Set environment variables for the container
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - WHISPER_MODEL=base
    # Connect host GPU devices to the container
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    volumes:
      - ~/.cache/whisper:/root/.cache/whisper

